#:schema node_modules/wrangler/config-schema.json
name = "hentges-ai"
compatibility_date = "2026-04-04"
pages_build_output_dir = "./dist"

[build.environment]
NODE_VERSION = "22"
PNPM_VERSION = "10.12.1"
